### ISSUE TITLE
Layer Count Calculated Wrong

### ISSUE THREAD

**Issue by Noou-Ben** [awe-source/OctoPrint-SkipTo#5]
When skipping to a z-height the counter showed the total layers left needing to print(663) however it started at around layer 330 on the layers done already when it should have started on 0. This meant the layer count completed although there was still 50% left to print
 
![image](https://github.com/user-attachments/assets/247ef337-2e24-4f64-9522-c4a3a808cee7)
![image](https://github.com/user-attachments/assets/b2e2a463-2130-4edd-b181-044b03b40d68)

**Comment by awe-source** [comment]
Yep... there is something VERY wrong with going by Z-HEIGHT in this version... will try to figure out why its soooo bad... 
in the meantime the "quick fix" that will get you most of the way there is go with layers, and GUEStimate with "Xmm / layer height" (note that in the "lower layers" there's usually a different first layer (or two) so you may need to "under"guestimate... 

eg if you GENERAL layer height is 0.4 then depending on your firs layer(s) you may want to use "0.38 or 0.42" or something like that...

anyway... hopefully will fix this soon and thanks again for raising it

**Comment by Noou-Ben** [comment]
@awe-source no problem at all. Was a bit confusing but honestly not a deal breaker. your plugin saved my print that had already gone for 18 hours so I was extremely happy.

Will experiement going by layer though! Thanks! :)

**Comment by awe-source** [comment]
Also related to this... somehow... randomly the base layer is not skipped... meaning the model will get knocked off by layer 0 being printed... need to figure out why and fix that too!

**Comment by awe-source** [comment]
This is being improved or fixed... hopefully it will fix both issues

**Comment by awe-source** [comment]
the display layer plugin shows this layer info, but we can't see why it would STOP the print before it was finished... technically it shouldn't have any "how many layers are there" unless some plugin or other is pulling it from metadata... if this is the case then that may be an issue we need to consider in this plugin in order to create a list of "empty layers" so that the layercount remains the same, just no OPERATIONS below a certian Z/Layer - rather than just eliminating the layers complely (whcih is what is currently done)

the way the layers are "extracted" effectively means that the NEW output starts from "0" again (but at a different z height)... 
I'm about to upload a new version, but if you can provide the files and we can fiddle with them, we might be able to understand how its going wrong (next time can you include the "skipto" layer info - and perhaps this is redundant given the existence of plugins like this display one that are specifically for this - thoughts on this are welcome also)

**Comment by awe-source** [comment]
okay... IF you are not talking about "50% left to print" in REALITY (ie the model printed the full set of remaining layers, it just LOOKS like it didn't accordin to the "layer marker" AND this is the "displayplugin" that I think it is then there are a few things at hand:

1 the way the display plugin works (mostly guessing) is to process your gcode upon loading (I think) and adds file markers per layer (modifying the file permanently) with "layerx" values that it uses to display total and values
2 because of this IF you choose to "skip to" then these markers are already in the file and you can't get rid of them without reloading the original gcode file - since the skipto plugin modifies this "after its loaded" then we're stuck with these without accomodating its nuances also
3 there is a bug/feature in that plugin that doesn't total/count correctly in cura files (and maybe others) becuase its first layer is 0 so it will always be 1 out (so a 200layer file will display as 199) - this is irrelevant to this specific issue, but its a thing...

I'm not sure there is much we can do about this.
if you have thoughts or ideas let us know - but getting a plugin to account for or affect another plugin sounds like a recipe for disaster to me.

NOTE there is a "layer/z" display near the "Start Print At" button... it wasn't in your screen shot, but its (maybe) just below what you captured... not sure if this helps or hinders or is more confusing than helpful, but as always feedback is welcome.

**Comment by awe-source** [comment]
NOTE: Just released v0.1.4
This handles things differently... so would love feedback on that/this issue.

it basiclally ELIMINATES the skipped layers, which in theory causes this challenging issue... however what (may) work is that in each skipped layer we replace operations with a single "do nothign" gcode line, this might tell the processor, and plugins such as this one, that it IS a layer and that it SHOUDL be counted, but its nto going to hurt the existing print...


Please let us know if you like this thought or not

Update: 0.1.5 now does the "do nothign" and from a few breif tests, it appears to solve this issue for this plugin

**Comment by Noou-Ben** [comment]
@awe-source I tried this last night and it seemed to work perfectly! Absolutely awesome work!
